spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

logging:
  level:
    org:
      hibernate:
        SQL: debug

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      auto: false
      static: ap-northeast-2
    s3:
      bucket: ootw-clothes
    stack:
      auto: false

oauth:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: ${KAKAO_REDIRECT_URI}
    client_secret: ${KAKAO_CLIENT_SECRET}
    scope: profile_nickname, account_email

weather:
  url:
    past: https://www.weatheri.co.kr/bygone/pastDB_tmp.php
    today: https://www.weatheri.co.kr/forecast/forecast01.php
  weight: 1.5
  api:
    auth_key: ${WEATHER_API_AUTH_KEY}

jwt:
  secret_key: ${JWT_SECRET_KEY}
  expiration_time_hour: 72
